### ISSUE TITLE
AttributeError: module 'matplotlib.cm' has no attribute 'get_cmap'

### ISSUE THREAD

**Issue by melodicdeath** [mcuntz/ncvue#8]
Hi,I seem to have found a bug in 4.4.1, which may be related to the version of matplotlib. I roll back the version from matplotlib-3.9.0 to matplotlib-3.8.4 and it will work normally.

Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/micromamba/envs/ncvue/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/home/micromamba/envs/ncvue/lib/python3.9/site-packages/ncvue/ncvmap.py", line 797, in selected_v
    self.redraw()
  File "/home/micromamba/envs/ncvue/lib/python3.9/site-packages/ncvue/ncvmap.py", line 1290, in redraw
    self.ncmap   = mpl.cm.get_cmap(self.icmap).N
AttributeError: module 'matplotlib.cm' has no attribute 'get_cmap'

**Comment by mcuntz** [comment]
Sorry for the late reply. I was on holiday :-)

Thanks for the bug report. I corrected it and bumped to v4.4.2 on PyPI and conda-forge.
Strange that matplotlib did not throw a deprecation warning with versions 3.8.x.
